import MyHeader from "../../../components/MyHeader";

export const metadata = {
  title: "Your App Dashboard",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <div>
      <MyHeader />
      <main>{children}</main>
    </div>
  );
}
