import Sidebar from "../../../components/Sidebar";

export const metadata = {
  title: "Your App Dashboard",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <div>
      <div className="flex flex-row">
        <Sidebar />
        <main className=" w-[100%]">{children}</main>
      </div>
    </div>
  );
}
