version: "3.8"
services:
  app:
    build: ./backend
    command: sh -c "npx prisma migrate deploy && npx nodemon main.js"
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis_sessions
      - redis_pubsub
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_sessions:
    image: "redis:alpine"

  redis_pubsub:
    image: "redis:alpine"

volumes:
  postgres_data:
