version: "3.8"
services:
  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npx nodemon main.js"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis_sessions
      - redis_pubsub
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_sessions:
    image: "redis:alpine"

  redis_pubsub:
    image: "redis:alpine"

volumes:
  postgres_data:
