import React from "react";
import MyHeader from "../../components/MyHeader";

export const metadata = {
  title: "Your account",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div>
      <MyHeader />
      <main>{children}</main>
    </div>
  );
}
